### ISSUE TITLE
excel2table source tarball: No such file or directory: 'CHANGELOG.rst'

### ISSUE THREAD

**Issue by jayvdb** [pyexcel/pyexcel-sortable#1]
https://github.com/pyexcel/excel2table has issues disabled ..
and it has two commits merged, so that repo is out of date with its upstream

```py
> py2pack generate excel2table
generating spec file for excel2table...
Traceback (most recent call last):
  File "setup.py", line 62, in <module>
    long_description=read_files("README.rst", "CHANGELOG.rst"),
  File "setup.py", line 13, in read_files
    content = read(single_file)
  File "setup.py", line 20, in read
    with open(afile, 'r') as opened_file:
FileNotFoundError: [Errno 2] No such file or directory: 'CHANGELOG.rst'
```

**Comment by jayvdb** [comment]
Also tag v2.2.1 is missing from https://github.com/pyexcel/excel2table/releases

**Comment by jayvdb** [comment]
Also excel2table needs tests in the sdist, etc.

excel2table is a high priority, as it needs to be completed and accepted into openSUSE before projects using it can be completed & submitted. ping @chfw

**Comment by chfw** [comment]
all done. v2.3.2 is the candidate
